spring.application.name=expense-api

# 1. Production Database Connection (Injected by Render)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Production Hibernate Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

# 3. Production Logging Visibility (Disabled for performance)
spring.jpa.show-sql=false

# Dynamic Port Binding for Render
server.port=${PORT:8080}
