spring.application.name=expense-api


# 1. Database Connection Engine Coordinates
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate Architecture Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


# 3. System Query Visibility
spring.jpa.show-sql=true
